name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rust-cargo
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
    - name: make
      run: make vm
    - name: make check
      run: make check
    - name: Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GHSECRET }}
        filename: tests.json
        label: Passing
        message: ${{ env.TEST_RESULT }}
