name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.17.0'
    - uses: ilammy/setup-nasm@v1
    - uses: Swatinem/rust-cache@v2
    - name: make
      run: make all
    - name: make check
      run: make check
    - name: VM Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        gistID: 2bc57fe31c6d742b25defe3549e78433
        auth: ${{ secrets.GHSECRET }}
        filename: tests.json
        label: bytecode
        message: ${{ env.TEST_RESULT }}
        valColorRange: ${{ env.COLOR }}
        maxColorRange: 100
        minColorRange: 0
    - name: AOT Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        gistID: 2bc57fe31c6d742b25defe3549e78433
        auth: ${{ secrets.GHSECRET }}
        filename: aot.json
        label: executable
        message: ${{ env.GO_TEST_RESULT }}
        valColorRange: ${{ env.GO_COLOR }}
        maxColorRange: 100
        minColorRange: 0
    - name: AOT Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        gistID: 2bc57fe31c6d742b25defe3549e78433
        auth: ${{ secrets.GHSECRET }}
        filename: aot.json
        label: executable
        message: ${{ env.AOT_TEST_RESULT }}
        valColorRange: ${{ env.AOT_COLOR }}
        maxColorRange: 100
        minColorRange: 0
