name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: make
      run: make all
    - name: make check
      run: make check
    - name: Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        gistID: 2bc57fe31c6d742b25defe3549e78433
        auth: ${{ secrets.GHSECRET }}
        filename: tests.json
        label: Passing
        message: ${{ env.TEST_RESULT }}
